codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 1%
        if_ci_failed: error

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

flags:
  unittests:
    paths:
      - designer2/
      - lib/
  integration:
    paths:
      - designer2/
      - lib/

ignore:
  - "tests/"
  - "docs/"
  - "examples/"
  - "setup.py"
  - "**/__pycache__/"
  - "build/"
  - "dist/"
