version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@1.3.0
workflows:
  detect-changes:
    jobs:
      - path-filtering/filter:
          name: compute-dockerfile-matches
          base-revision: main
          mapping: |
            docker_deps/Dockerfile_fsl     run_fsl    true
            docker_deps/Dockerfile_mrtrix3 run_mrtrix true
            docker_deps/Dockerfile_ants    run_ants   true
          config-path: .circleci/continue-config.yml
