version: 2.1

parameters:
  run_fsl:
    type: boolean
    default: false
  run_mrtrix:
    type: boolean
    default: false
  run_ants:
    type: boolean
    default: false

commands:
  run_build_dep_image:
    parameters:
      dep:
        type: string
      tag:
        type: string
    steps:
      - run:
          name: Build <<parameters.dep>> image
          command: |
            docker build \
              -f docker_deps/Dockerfile_<<parameters.dep>> \
              -t $DOCKERHUB_USERNAME/<<parameters.dep>>:<<parameters.tag>> \
              docker_deps
      - run:
          name: Test <<parameters.dep>> image
          command: |
            docker run --rm \
              $DOCKERHUB_USERNAME/<<parameters.dep>>:<<parameters.tag>> \
              echo "Image <<parameters.dep>> built successfully"
  run_build_designer_image:
    parameters:
      tag:
        type: string
      dependency_tag:
        type: string
    steps:
      - run:
          name: Build designer image
          command: |
            docker build \
              --build-arg DEPENDENCY_TAG=<<parameters.dependency_tag>> \
              -t $DOCKERHUB_USERNAME/designer2:<<parameters.tag>> .
      - run:
          name: Test designer command
          command: docker run --rm $DOCKERHUB_USERNAME/designer2:<<parameters.tag>> designer -version
      - run:
          name: Test fsl command
          command: docker run --rm $DOCKERHUB_USERNAME/designer2:<<parameters.tag>> flirt -version
      - run:
          name: Test mrtrix command
          command: docker run --rm $DOCKERHUB_USERNAME/designer2:<<parameters.tag>> mrinfo -version

jobs:
  build-and-push-fsl:
    parameters:
      tag:
        type: string
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - when:
          condition: << pipeline.parameters.run_fsl >>
          steps:
            - run_build_dep_image:
                dep: fsl
                tag: <<parameters.tag>>
  build-and-push-mrtrix:
    parameters:
      tag:
        type: string
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - when:
          condition: << pipeline.parameters.run_mrtrix >>
          steps:
            - run_build_dep_image:
                dep: mrtrix
                tag: <<parameters.tag>>
  build-and-push-ants:
    parameters:
      tag:
        type: string
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - when:
          condition: << pipeline.parameters.run_ants >>
          steps:
            - run_build_dep_image:
                dep: ants
                tag: <<parameters.tag>>
  build-and-push-designer:
    parameters:
      tag:
        type: string
      dependency_tag:
        type: string
        default: latest
      push_to_registry:
        type: boolean
        default: true
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run_build_designer_image:
          tag: <<parameters.tag>>
          dependency_tag: <<parameters.dependency_tag>>
      - when:
          condition: << parameters.push_to_registry >>
          steps:
            - run:
                name: Push designer image
                command: |
                  echo $DOCKERHUB_PASSWORD \
                    | docker login -u $DOCKERHUB_USERNAME --password-stdin
                  docker push $DOCKERHUB_USERNAME/designer2:<<parameters.tag>>

workflows:
  build-on-commit:
    jobs:
      - build-and-push-fsl:
          name: Build FSL on Commit
          tag: latest
          context: DockerHub
          filters:
            branches:
              ignore: main
      - build-and-push-mrtrix:
          name: Build MRtrix on Commit
          tag: latest
          context: DockerHub
          filters:
            branches:
              ignore: main
      - build-and-push-ants:
          name: Build ANTs on Commit
          tag: latest
          context: DockerHub
          filters:
            branches:
              ignore: main
      - build-and-push-designer:
          name: Build DESIGNER on Commit
          push_to_registry: false
          tag: build-test
          dependency_tag: latest
          context: DockerHub
          requires:
            - build-and-push-fsl
            - build-and-push-mrtrix
            - build-and-push-ants
          filters:
            branches:
              ignore: main
