FROM python:3.12.4-bookworm AS builder

# Install download/unpack tools
RUN --mount=type=cache,sharing=private,target=/var/cache/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends \
      curl \
      unzip \
    && rm -rf /var/lib/apt/lists/*

# Fetch the Ubuntu 22.04 X64 build of ANTs v2.5.4
WORKDIR /usr/local/ants
RUN curl -sSL \
      -o /tmp/ants.zip \
      https://github.com/ANTsX/ANTs/releases/download/v2.5.4/ants-2.5.4-ubuntu-22.04-X64-gcc.zip && \
    unzip /tmp/ants.zip && \
    mv ants-2.5.4/* . && \
    rm -rf /tmp/ants.zip ants-2.5.4


FROM docker.io/debian:bookworm-slim

RUN mkdir -p /usr/local/ants/bin/
RUN mkdir -p /usr/local/ants/lib/

# Only copy the N4BiasFieldCorrection binary and library
COPY --from=builder /usr/local/ants/bin/N4BiasFieldCorrection /usr/local/ants/bin/N4BiasFieldCorrection
COPY --from=builder /usr/local/ants/lib/libl_N4BiasFieldCorrection.a /usr/local/ants/lib/libl_N4BiasFieldCorrection.a
