FROM python:3.12.4-bookworm AS builder

# Install necessary dependencies
RUN --mount=type=cache,sharing=private,target=/var/cache/apt \
    apt-get update && \
    apt-get install -yq --no-install-recommends \
    g++-11 \
    cmake \
    make \
    ninja-build \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/local

ARG CC=gcc-11 CXX=g++-11 BUILD_SHARED_LIBS=ON

# Clone and build ANTs
# https://github.com/ANTsX/ANTs/wiki/Compiling-ANTs-on-Linux-and-Mac-OS
RUN git clone --branch v2.5.4 --single-branch https://github.com/stnava/ANTs.git
RUN mkdir build ants \
    && cd build \
    && cmake \
    -GNinja \
    -DCMAKE_INSTALL_PREFIX=/usr/local/ants \
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS} \
    -DBUILD_TESTING=OFF \
    -DRUN_LONG_TESTS=OFF \
    -DRUN_SHORT_TESTS=OFF \
    ../ANTs \
    && cmake --build . --parallel 
WORKDIR /usr/local/build/ANTS-build 
RUN cmake --install .


FROM docker.io/debian:bookworm-slim AS base
COPY --from=builder /usr/local/ants /usr/local/ants
