# docker build for distributing a base fs 7.2.0 container

FROM python:3.12.1-bookworm

# shell settings
WORKDIR /root

# install utils
RUN yum -y update
RUN yum -y install bc libgomp perl tar tcsh wget vim-common
RUN yum -y install mesa-libGL libXext libSM libXrender libXmu
RUN yum clean all

# install fs
RUN wget https://surfer.nmr.mgh.harvard.edu/pub/dist/freesurfer/7.2.0/freesurfer-linux-centos7_x86_64-7.2.0.tar.gz -O fs.tar.gz && \
    tar --no-same-owner -xzvf fs.tar.gz && \
    mv freesurfer /usr/local && \
    rm fs.tar.gz
