source "https://rubygems.org"
gemspec

gem "jekyll-github-metadata", ">= 2.15"
gem "jekyll-include-cache", group: :jekyll_plugins
gem "html-proofer", "~> 5.0", :group => :development

gem "nokogiri", ">= 1.16.5"
gem "rexml", ">= 3.2.7"