name: Run Tests

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image with cache
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: designer-test:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run tests in Docker
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          designer-test:latest \
          bash -c "
            pip install -r tests/test_requirements.txt && \
            pytest -s --dist loadscope -n 2 tests/test_e2e_meso_degibbs.py tests/test_e2e_heal_coronal.py
          "
# TODO: use 4 cores and include all tests
